# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: City of Austin Office of Design & Delivery
email: innovationfellows@austintexas.gov
description: 
  We’re a new office within the City of Austin
  that’s dedicated to designing and building services 
  for residents that grow and adapt with their needs. 
baseurl: /innovation-fellows # the base hostname & protocol for your site
twitter_username: civiqueso
github_username:  cityofaustin
image: /innovation-fellows/assets/img/home.jpg
medium_url: https://medium.com/civiqueso
zilker_theme: dark
theme: minima
# dark is the default, light will also work.

nav_from_collection:

# Build settings
markdown: kramdown
collections:
  projects:
    title: Projects
    output: false
  press:
    title: Press mentions
    output: false
  events:
    title: Events
    output: false
  people:
    title: Staff
    output: false
  jobs:
    title: Jobs
    output: true
    permalink: /join/:path/

defaults:
- scope:
    path: ''
    type: jobs
  values:
    layout: 'sidebar-page'
    nav_from_collection: 'Jobs'
- scope:
    path: ''
    type: projects
  values:
    image_path: '/assets/img/projects/project-tile-placeholder.jpg'

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Jekyll SEO Tag
# See https://github.com/jekyll/jekyll-seo-tag


# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: assets/stylesheets/
permalink: pretty
exclude:
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - /screenshots
  - /assets/stylesheets/bourbon
  - /assets/stylesheets/bourbon-neat
  - /assets/uswds/stylesheets
  - /assets/uswds/js
  - .bundle
  - /vendor
  - _bourbon
  - _bourbon-neat
  - _uswds



twitter:
  username: civiqueso
logo: /img/dti-fellows-logo.png
